apiVersion: v1
kind: Service
metadata:
    name: myapp-db-svc
spec:
    selector:
        app: myapp
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 1433
          targetPort: 1433