version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password_123"
      MSSQL_PID: "Express"
  frontend:
    build: ./
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./src:/app/src
    depends_on:
      - sqlserver